In [75]:
import numpy as np 
from sklearn import preprocessing 

In [76]:
data_train=np.genfromtxt("training_boston_x_y_train.csv",delimiter=',')
data_train

array([[-0.40784991, -0.48772236, -1.2660231 , ...,  0.41057102,
        -1.09799011, 37.9       ],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.29116915,
        -0.52047412, 21.4       ],
       [ 0.1251786 , -0.48772236,  1.01599907, ..., -3.79579542,
         0.89107588, 12.7       ],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.33206621,
        -0.33404299, 20.8       ],
       [-0.41061997, -0.48772236, -1.15221381, ...,  0.203235  ,
        -0.74475218, 22.6       ],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.38787479,
        -1.35871335, 50.        ]])

In [77]:
data_test=np.genfromtxt("test_boston_x_test.csv",delimiter=',')
data_test

array([[ 2.91816626, -0.48772236,  1.01599907, ...,  0.80657583,
        -1.59755122,  1.04106182],
       [-0.40339151, -0.48772236,  0.40609801, ..., -1.13534664,
         0.44105193, -0.89473812],
       [-0.4131781 , -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.50084979],
       ...,
       [-0.41001449,  2.08745172, -1.37837329, ..., -0.0719129 ,
         0.39094481, -0.68167397],
       [-0.40317611, -0.48772236, -0.37597609, ...,  1.13022958,
         0.34007019,  0.20142086],
       [-0.13356344, -0.48772236,  1.2319449 , ..., -1.73641788,
        -2.93893082,  0.48877712]])

In [78]:
print(data_train.shape)
print(data_test.shape)

(379, 14)
(127, 13)


In [30]:
#x_train=data_train[:,:-1]
#x_train.shape

In [31]:
#y_train=data_train[:,-1]
#y_train.shape

In [24]:
#scaler=preprocessing.StandardScaler()
#scaler.fit(x_train)
#scaler.transform(x_train)

array([[-0.40098068, -0.49042688, -1.28149216, ..., -0.32264241,
         0.42027996, -1.10095452],
       [-0.40053396, -0.49042688,  0.20753471, ...,  0.09391068,
         0.30257958, -0.53143278],
       [ 0.09900799, -0.49042688,  0.96425328, ...,  0.78816582,
        -3.72614514,  0.86057789],
       ...,
       [-0.40141319, -0.49042688,  0.20753471, ...,  0.09391068,
         0.34289385, -0.34758231],
       [-0.40357903, -0.49042688, -1.16949207, ..., -0.7391955 ,
         0.21589851, -0.75260628],
       [ 0.30324229, -0.49042688,  0.96425328, ...,  0.78816582,
         0.39790715, -1.35806871]])

In [79]:
def predict(x,m,c):
    N = x.shape[0]
    y=np.zeros(N)
    
    for i in range(N):
        X=x[i,:]
        y[i] = (m * X).sum() + c
    return y

In [80]:
def step_gradient(points, learning_rate, M):
    N=points.shape[0] #no. of rows 
    num_col=points.shape[1] #no. of columns 
    new_M=np.zeros(num_col)
    for i in range(N):
        x = points[i, 0:num_col-1]
        x=np.append(x,1) # 
        #print(x.shape) #array extra column of 1 
        y = points[i, num_col-1]
        for j in range(num_col):
            new_M[j] += (-2/N)*(y - (M * x).sum()) * x[j]
        M = M - (learning_rate*new_M)
    return M

In [81]:
def gd(points, learning_rate, num_iterations):
    num_col=points.shape[1] # giving rows
    M=np.zeros(num_col)
    for i in range(num_iterations):
        M = step_gradient(points, learning_rate,M)
    print(i, " Cost: ", cost(points, M))
    return M

In [82]:
def cost(points,M):
    total_cost = 0
    N=points.shape[0] #rows
    num_col=points.shape[1] #columns
    for i in range(N):
        x=points[i,0:num_col-1]
        x=np.append(x,1)
        y=points[i,num_col-1]
        total_cost += (y- (M * x).sum()) ** 2
    total_cost = (1/N) * total_cost
    return total_cost 

In [83]:
def run():
    learning_rate = 0.00001
    num_iterations = 1000
    m= gd(data_train, learning_rate, num_iterations)
    #y_pred=predict(data_test,m,c)
    return m[0:13], m[13]
    
  

In [84]:
m,c=run()
print(m,c)

999  Cost:  25.571325690101485
[-0.84556523  0.40130442 -0.82525659  0.76445869 -0.65678052  3.2496442
  0.210736   -1.49828066  0.79231793 -0.36078684 -1.54200284  0.66263159
 -3.58986573] 22.013737506684336


In [85]:
test_data = np.genfromtxt("test_boston_x_test.csv", delimiter = ",")

In [86]:
from sklearn.ensemble import GradientBoostingRegressor

In [87]:
x_train=data_train[:,:-1]
x_train.shape

(379, 13)

In [88]:
y_train=data_train[:,-1]
y_train.shape

(379,)

In [89]:
#scaler=preprocessing.StandardScaler()
#scaler.fit(x_train)
#scaler.transform(x_train)

In [90]:
reg=GradientBoostingRegressor()
reg.fit(x_train,y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [98]:
y_pred=predict(test_data,m,c)

In [99]:
y_pred

array([ 9.36458138, 27.28636875, 21.91923176, 23.25353665, 20.65089313,
        2.9891675 , 28.17890497, 23.44309366, 18.60911878, 22.15868737,
       24.00497038, 18.42077799, 19.56131075, 21.0051007 , 41.75677689,
       23.31769034, 22.98050169, 26.62449631, 19.76582152, 30.97168641,
       23.082548  , 22.30301218, 31.55165339, 33.88068576, 31.6927709 ,
       14.09781081, 21.17698184, 30.922773  , 22.92632988, 32.26887677,
       17.84738273, 24.23811396, 23.58171369, 25.00655168, 14.75966483,
       27.85326534, 25.19738794, 20.45011688, 23.58309134,  9.83820425,
        4.89568442, 27.04454058, 28.40533968, 20.24754439, 19.52958177,
        1.25643133, 39.89081685, 25.45984426, 30.79493094, 17.40223121,
       16.76562868, 38.73355419, 18.16958608, 19.97054367, 16.77201583,
       21.10877228, 18.07249456, 21.95402325, 14.39021031, 17.22138929,
       13.90725075, 28.32332977, 24.0622698 , 25.07200831, 16.06425072,
       14.47392181, 33.7315911 , 17.25734212, 24.38846247, 21.25

In [112]:
y_pred.mean()

22.059263368548823

In [95]:
#for i in range (0,len(y_pred)):
#    y_pred[i]="{0:.8f}".format(float(y_pred[i]))
#    print(y_pred[i])

In [109]:
np.savetxt("finalPredictions4.csv",y_pred,delimiter=',')